BEGIN;

-- Time-series observations (TimescaleDB hypertable, 7-day chunks)
CREATE TABLE IF NOT EXISTS observations (
    time         TIMESTAMPTZ      NOT NULL,
    asset_id     UUID             NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    metric       TEXT             NOT NULL,
    value        DOUBLE PRECISION NOT NULL,
    unit         TEXT,
    quality_flag SMALLINT         NOT NULL DEFAULT 0 CHECK (quality_flag IN (0, 1, 2)),
    source       TEXT             NOT NULL DEFAULT 'sensor'
);

SELECT create_hypertable(
    'observations', 'time',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists       => TRUE
);

-- Asset alerts generated by anomaly detection
CREATE TABLE IF NOT EXISTS asset_alerts (
    alert_id    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    asset_id    UUID NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    time        TIMESTAMPTZ NOT NULL DEFAULT now(),
    alert_type  TEXT NOT NULL,
    severity    INT  NOT NULL CHECK (severity BETWEEN 1 AND 5),
    message     TEXT NOT NULL,
    metric      TEXT,
    value       FLOAT,
    threshold   FLOAT,
    resolved    BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at TIMESTAMPTZ
);

-- ML risk scores + SHAP attribution per asset
CREATE TABLE IF NOT EXISTS risk_scores (
    score_id      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    asset_id      UUID NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    scored_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    risk_score    FLOAT NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    risk_tier     TEXT  NOT NULL CHECK (risk_tier IN ('critical','high','medium','low')),
    model_version TEXT  NOT NULL DEFAULT 'v1',
    shap_values   JSONB,
    features_used JSONB,
    anomaly_flag  BOOLEAN NOT NULL DEFAULT FALSE,
    anomaly_types TEXT[],
    notes         TEXT
);

-- Spatial cluster zones computed by HDBSCAN
CREATE TABLE IF NOT EXISTS cluster_zones (
    zone_id        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    region_code    TEXT REFERENCES regions(code),
    geometry       GEOMETRY(Polygon, 4326) NOT NULL,
    cluster_id     INT  NOT NULL,
    asset_count    INT,
    avg_risk       FLOAT,
    dominant_class TEXT,
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Prioritised inspection queue (rebuilt on each pipeline run)
CREATE TABLE IF NOT EXISTS inspection_queue (
    queue_id        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    asset_id        UUID NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    region_code     TEXT REFERENCES regions(code),
    priority_rank   INT  NOT NULL,
    priority_score  FLOAT NOT NULL,
    risk_tier       TEXT,
    reason_codes    TEXT[],
    recommended_date DATE,
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    status          TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','scheduled','completed','cancelled'))
);

-- Audit log for every LLM explanation request
CREATE TABLE IF NOT EXISTS explanation_log (
    log_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    asset_id     UUID REFERENCES assets(asset_id) ON DELETE SET NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    template     TEXT NOT NULL,
    context      JSONB,
    explanation  TEXT NOT NULL,
    model        TEXT NOT NULL DEFAULT 'llama3.2',
    latency_ms   INT,
    source_ip    TEXT,
    request_id   TEXT
);

COMMIT;
